'use strict';

module.exports = [
  {
    ignores: [
      'libraries/**',
      'node_modules/**',
      'attached_assets/**',
      '_ref_frames/**',
      'docs/**',
      'tools/**',
      '**/*.min.js',
      '**/*.mjs',
    ],
  },
  {
    languageOptions: {
      ecmaVersion: 2022,
      sourceType: 'script',
      globals: {
        window: 'readonly',
        document: 'readonly',
        console: 'readonly',
        location: 'readonly',
        history: 'readonly',
        navigator: 'readonly',
        localStorage: 'readonly',
        sessionStorage: 'readonly',
        fetch: 'readonly',
        URL: 'readonly',
        URLSearchParams: 'readonly',
        Blob: 'readonly',
        FileReader: 'readonly',
        Worker: 'readonly',
        Image: 'readonly',
        ImageData: 'readonly',
        DOMParser: 'readonly',
        AudioContext: 'readonly',
        WebGL2RenderingContext: 'readonly',
        requestAnimationFrame: 'readonly',
        cancelAnimationFrame: 'readonly',
        setTimeout: 'readonly',
        clearTimeout: 'readonly',
        setInterval: 'readonly',
        clearInterval: 'readonly',
        btoa: 'readonly',
        atob: 'readonly',
        escape: 'readonly',
        unescape: 'readonly',
        alert: 'readonly',
        prompt: 'readonly',
        confirm: 'readonly',
        performance: 'readonly',
        Float32Array: 'readonly',
        Uint8Array: 'readonly',
        Uint32Array: 'readonly',
        ArrayBuffer: 'readonly',
        DataView: 'readonly',
        Map: 'readonly',
        Set: 'readonly',
        Promise: 'readonly',
        JSON: 'readonly',
        Math: 'readonly',
        Date: 'readonly',
        Error: 'readonly',
        TypeError: 'readonly',
        Infinity: 'readonly',
        NaN: 'readonly',
        isNaN: 'readonly',
        parseFloat: 'readonly',
        parseInt: 'readonly',
        encodeURIComponent: 'readonly',
        decodeURIComponent: 'readonly',
        module: 'readonly',
        require: 'readonly',
        exports: 'readonly',
        process: 'readonly',
        Buffer: 'readonly',
        __dirname: 'readonly',
        __filename: 'readonly',
        global: 'readonly',
        globalThis: 'readonly',
        self: 'readonly',
        crypto: 'readonly',
        WebSocket: 'readonly',
        postMessage: 'readonly',
        onmessage: 'writable',
        pako: 'readonly',
        dat: 'readonly',
        Chart: 'readonly',
        WeatherSandbox: 'readonly',
        WeatherMpProtocol: 'readonly',
        WeatherMultiplayer: 'writable',
        UserInteraction: 'writable',
        LightningV2: 'writable',
        ControlHelp: 'writable',
        SOUNDING_ANALOG_PRESETS: 'readonly',
        AviationTraffic: 'writable',
        debugLog: 'readonly',
        setWeatherDebugEnabled: 'readonly',
        isWeatherDebugEnabled: 'readonly',
        sanitizeCssColor: 'readonly',
        safeJsonParse: 'readonly',
        clamp: 'readonly',
        mod: 'readonly',
        map_range: 'readonly',
        map_range_C: 'readonly',
        download: 'readonly',
        getRadarWaterPixelsBuffer: 'readonly',
        getCompositeRadarBuffers: 'readonly',
        getSoundingGraphImgUrl: 'readonly',
        scrapeTableData: 'readonly',
        loadSounding: 'readonly',
      },
    },
    rules: {
      'no-unused-vars': ['warn', {
        argsIgnorePattern: '^_',
        varsIgnorePattern: '^_',
        caughtErrors: 'none',
      }],
      'no-undef': 'warn',
      'no-empty': ['warn', { allowEmptyCatch: true }],
      'no-console': 'off',
      'no-redeclare': 'off',
      'no-useless-escape': 'warn',
      'no-constant-condition': 'warn',
      'no-fallthrough': 'warn',
    },
  },
];
